version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: hits
      POSTGRES_PASSWORD: hits
      POSTGRES_DB: hitsdb
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
