version: "3.9"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_USER: hits
      MYSQL_ROOT_PASSWORD: hits
      MYSQL_DATABASE: hitsdb
    ports:
      - "3306:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
